In [ ]:
import pandas as pd

# read_csv always returns a DataFrame
df = pd.read_csv(r'D:\actors.csv')
df.head(1000)

,Name,Nationality,Birth Year,Known For,Genre,Active Since,Awards
0,Tom Hanks,American,1956,Forrest Gump,Drama/Comedy,1980,2 Oscars
1,Leonardo DiCaprio,American,1974,The Revenant,Drama/Thriller,1991,1 Oscar
2,Meryl Streep,American,1949,The Devil Wears Prada,Drama,1977,3 Oscars
3,Cate Blanchett,Australian,1969,Blue Jasmine,Drama,1992,2 Oscars
4,Denzel Washington,American,1954,Training Day,Drama/Action,1981,2 Oscars
5,Natalie Portman,Israeli-American,1981,Black Swan,Drama/Thriller,1994,1 Oscar
6,Brad Pitt,American,1963,Fight Club,Drama/Action,1987,1 Oscar
7,Viola Davis,American,1965,Fences,Drama,1996,1 Oscar
8,Morgan Freeman,American,1937,The Shawshank Redemption,Drama,1964,1 Oscar
9,Scarlett Johansson,American,1984,Marriage Story,Drama/Action,1994,0 Oscars
10,Anthony Hopkins,Welsh,1937,The Silence of the Lambs,Thriller/Drama,1967,2 Oscars
11,Charlize Theron,South African,1975,Monster,Drama/Action,1995,1 Oscar

In [1]:
# Selecting a column after reading returns a Series, not a DataFrame
s1 = pd.read_csv(r'D:\actors.csv')['Name']
print(s1)

NameError: name 'pd' is not defined

In [3]:
# header=None tells pandas the file has no header row,
# so columns get assigned integer indices (0, 1, 2, ...) instead
df_without_header = pd.read_csv(r'D:\actors_no_header.csv', header=None)
df_without_header.head()

,0,1,2,3,4,5,6
0,Tom Hanks,American,1956,Forrest Gump,Drama/Comedy,1980,2 Oscars
1,Leonardo DiCaprio,American,1974,The Revenant,Drama/Thriller,1991,1 Oscar
2,Meryl Streep,American,1949,The Devil Wears Prada,Drama,1977,3 Oscars
3,Cate Blanchett,Australian,1969,Blue Jasmine,Drama,1992,2 Oscars
4,Denzel Washington,American,1954,Training Day,Drama/Action,1981,2 Oscars

In [4]:
# Use 'names' to assign custom column names to a headerless file
df_custom_names = pd.read_csv(r'D:\actors_no_header.csv', names=["Name", "Nationality", "Birth Year", "x", "y", "z"])
df_custom_names.head()

,Name,Nationality,Birth Year,x,y,z
Tom Hanks,American,1956,Forrest Gump,Drama/Comedy,1980,2 Oscars
Leonardo DiCaprio,American,1974,The Revenant,Drama/Thriller,1991,1 Oscar
Meryl Streep,American,1949,The Devil Wears Prada,Drama,1977,3 Oscars
Cate Blanchett,Australian,1969,Blue Jasmine,Drama,1992,2 Oscars
Denzel Washington,American,1954,Training Day,Drama/Action,1981,2 Oscars

In [5]:
# index_col sets a column as the row index instead of the default 0, 1, 2...
# Now you can access rows directly by actor name using .loc
df_indexed = pd.read_csv(r'D:\actors.csv', index_col='Name')
df_indexed.loc['Tom Hanks']

Nationality         American
Birth Year              1956
Known For       Forrest Gump
Genre           Drama/Comedy
Active Since            1980
Awards              2 Oscars
Name: Tom Hanks, dtype: object

In [6]:
# skiprows skips specific row numbers (0-indexed) when reading
df_skipped = pd.read_csv(r'D:\actors.csv', skiprows=[0, 2])
df_skipped.head()

,Tom Hanks,American,1956,Forrest Gump,Drama/Comedy,1980,2 Oscars
0,Meryl Streep,American,1949,The Devil Wears Prada,Drama,1977,3 Oscars
1,Cate Blanchett,Australian,1969,Blue Jasmine,Drama,1992,2 Oscars
2,Denzel Washington,American,1954,Training Day,Drama/Action,1981,2 Oscars
3,Natalie Portman,Israeli-American,1981,Black Swan,Drama/Thriller,1994,1 Oscar
4,Brad Pitt,American,1963,Fight Club,Drama/Action,1987,1 Oscar

In [ ]:
#nrows is only read number of rows and the rest fo the file is igonred
data = pd.read_csv(r'D:\actors_100.csv',nrows=20)

#it returns a reader object you loop over. Each iteration gives you the next chunk as a DataFrame
chunks  = pd.read_csv(r'D:\actors_100.csv',chunksize=5)
for chunk in chunks:
    print(chunk)
# NOW it reads 10,000 rows from disk
# processes them
# next iteration: previous chunk gone, next 10,000 loaded